"""
JSON report exporter — serializes :class:`~ds_data_miner.core.contracts.DatasetReport`
to standardized JSON files and auto-generates the corresponding JSON Schema.

**Agent Usage**

Use :class:`ReportExporter` when:

- You have a :class:`~ds_data_miner.core.contracts.DatasetReport` in memory
  (from :class:`~ds_data_miner.profiling.engine.ProfilingEngine` or
  :class:`~ds_data_miner.pandas_ext.accessor.MinerAccessor`) and want to
  persist it to disk.
- You want to generate the **JSON Schema** for downstream consumers
  (``ds-data-miner-vis``, ``ds-data-miner-reporter``, validators).

If you are using Pandas, prefer calling ``df.miner.export_json(path)`` which
runs the scan **and** export in one call without creating a
:class:`ReportExporter` manually.
"""

from __future__ import annotations

import json
from pathlib import Path

from ds_data_miner.core.contracts import DatasetReport


class ReportExporter:
    """Serialize a :class:`~ds_data_miner.core.contracts.DatasetReport` to a
    standardized JSON file with NaN/Inf → ``null`` conversion.

    All floating-point ``NaN`` and ``Inf`` values in the report are
    automatically converted to JSON ``null`` by Pydantic v2's
    ``ser_json_inf_nan="null"`` configuration — no manual pre-processing
    is required.

    Example — export + schema generation:

    .. code-block:: python

        from ds_data_miner.export.serializer import ReportExporter

        exporter = ReportExporter()
        exporter.export(report, "output/report.json")
        ReportExporter.export_schema("output/report.schema.json")

    Example — round-trip verification:

    .. code-block:: python

        from ds_data_miner.core.contracts import DatasetReport

        exporter.export(report, "report.json")
        restored = DatasetReport.model_validate_json(
            open("report.json").read()
        )
        assert restored == report
    """

    def export(
        self,
        report: DatasetReport,
        path: str | Path,
        *,
        indent: int = 2,
    ) -> None:
        """Write a :class:`~ds_data_miner.core.contracts.DatasetReport` to a JSON file.

        The output file is UTF-8 encoded.  Parent directories are created
        automatically.  NaN and Inf values are serialized as JSON ``null``.

        :param report: The dataset report to serialize.
        :param path: Output file path (``str`` or :class:`pathlib.Path`).
            Parent directories are created if they do not exist.
        :param indent: JSON indentation level.  Default ``2`` (pretty-printed).
            Set to ``0`` for compact single-line output.

        Example::

            exporter = ReportExporter()
            exporter.export(report, "reports/my_report.json")
            # File is valid JSON; NaN values appear as null
        """
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        json_str = report.model_dump_json(indent=indent)
        path.write_text(json_str, encoding="utf-8")

    @staticmethod
    def export_schema(path: str | Path) -> None:
        """Write the JSON Schema for :class:`~ds_data_miner.core.contracts.DatasetReport`.

        The schema is auto-generated by Pydantic v2's ``model_json_schema()``
        and includes all nested contract definitions
        (:class:`~ds_data_miner.core.contracts.DistributionProfile`,
        :class:`~ds_data_miner.core.contracts.CategoricalProfile`,
        :class:`~ds_data_miner.core.contracts.DatetimeProfile`).

        Downstream consumers (``ds-data-miner-vis``, ``ds-data-miner-reporter``,
        custom validators) can use this schema to validate report files before
        reading them.

        :param path: Output file path for the JSON Schema document.

        Example::

            ReportExporter.export_schema("schemas/report.schema.json")
            # schema contains $defs for all profile types
        """
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        schema = DatasetReport.model_json_schema()
        path.write_text(
            json.dumps(schema, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
