"""
JSON report exporter.

Serializes :class:`DatasetReport` to formatted JSON files, handling
NaN/Inf → null conversion via Pydantic v2's built-in configuration.
"""

from __future__ import annotations

import json
from pathlib import Path

from ds_data_miner.core.contracts import DatasetReport


class ReportExporter:
    """Serialize a :class:`DatasetReport` to a standardized JSON file.

    Usage::

        exporter = ReportExporter()
        exporter.export(report, "output/report.json")
        exporter.export_schema("output/report.schema.json")
    """

    def export(
        self,
        report: DatasetReport,
        path: str | Path,
        *,
        indent: int = 2,
    ) -> None:
        """Write a :class:`DatasetReport` to a JSON file.

        :param report: The dataset report to serialize.
        :param path: Output file path (parent dirs created automatically).
        :param indent: JSON indentation level (default 2 spaces).
        """
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        json_str = report.model_dump_json(indent=indent)
        path.write_text(json_str, encoding="utf-8")

    @staticmethod
    def export_schema(path: str | Path) -> None:
        """Write the JSON Schema for :class:`DatasetReport`.

        The schema is auto-generated by Pydantic's
        ``model_json_schema()`` and can be used by downstream consumers
        (``ds-data-miner-vis``, ``ds-data-miner-reporter``) for
        validation.

        :param path: Output file path.
        """
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        schema = DatasetReport.model_json_schema()
        path.write_text(
            json.dumps(schema, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
